### PR TITLE
(SIMP-7824) deep merge hash values

### PR DESCRIPTION
**Pull request by silug**
Prior to this change, hash values were merged using `merge`, causing
unexpected behavior with nested hashes.  This change fixes that by using
`deep_merge!` for hash values.

In addition, this refactors the logic that handles merging to make it
more clear, calls `raise` if there is a type mismatch when merging
(where previously the behavior was undefined), returns less extraneous
data in the Hiera backend, breaks up the
`compliance_markup::enforcement` `lookup()` tests, and adds tests for
merge behavior.

SIMP-7824 #close

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@silug I'm ok with this personally since I think it's what we all expect the code to do in general. However, this is a breaking change so should probably have an opt-in flag for deep merge behavior.

**Comment by silug** [comment]
> @silug I'm ok with this personally since I think it's what we all expect the code to do in general.

Yeah, I honestly consider the current behavior to be a bug based on everything I've been told and everything I've told customers.

> However, this is a breaking change so should probably have an opt-in flag for deep merge behavior.

There was a comment in there (before I started) about needing to implement merge settings.  Unfortunately, I'm not sure where to even start to implement something like that.

**Comment by trevor-vaughan** [comment]
What does the README say? If it doesn't say anything then I guess the behavior was indeterminate and we should update the README.

**Comment by trevor-vaughan** [comment]
@silug Just did a quick search and there doesn't seem to be a mention of how things get merged anywhere in the documentation in the module or in `simp-doc` that I can find so this isn't breaking because it was a complete mystery.

Would you mind updating the README (or something) though?

**Comment by silug** [comment]
> Would you mind updating the README (or something) though?

Done.  Let me know if that's the kind of thing that you were talking about.

**Comment by trevor-vaughan** [comment]
Works for me. At least it's documented somewhere now.

**Pull request merged**
