### PR TITLE
(SIMP-8229) Add controls, identifiers, and oval-ids

### PR DESCRIPTION
**Pull request by silug**
SIMP-8229 #close

### CODE REVIEW

**Comment by kendall-moore** [comment]
Confirmed on a test system this adds identifiers and controls back to the reports.

**Review by kendall-moore — APPROVED** [review]

**Comment by trevor-vaughan** [comment]
@silug Looks like you need a version bump.

Also, was this run against something like `auditd` just so it's hit something with deeper internal tests?

**Review by kendall-moore — APPROVED** [review]

**Review by michael-riddle — APPROVED** [review]
Walked through this issue with Steve and saw where it was breaking in newer puppet versions. Approving the new testing method.

**Comment by silug** [comment]
> @silug Looks like you need a version bump.

Done.  (I'll have to rebase #109 once this is merged.)

> Also, was this run against something like `auditd` just so it's hit something with deeper internal tests?

That and our Windows module.

**Review by ayohrling — APPROVED** [review]

**Pull request merged**
