### PR TITLE
Issue 143

### PR DESCRIPTION
**Pull request by michael-riddle**
Allow users to do a negative confine by placing a '--' in front of the term they do not want to match against.

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@michael-riddle This is nice!

Would you mind if we changed it to a `!` so that it's not confused with an actual knockout prefix (and/or doesn't get in the way of using the regular knockout prefix if it comes into play later)?

**Comment by michael-riddle** [comment]
> @michael-riddle This is nice!
> 
> Would you mind if we changed it to a `!` so that it's not confused with an actual knockout prefix (and/or doesn't get in the way of using the regular knockout prefix if it comes into play later)?

In regard to this, there's a ticket out there to make knockout prefixes configurable, once that is worked out I don't see how the same logic couldn't be applied in this instance for the negative confine. https://github.com/simp/pupmod-simp-compliance_markup/issues/146 for reference.

We don't believe there will be any conflicts between the confine and knockout prefix even if they're the same at the moment. Are there any specific examples of this being an issue you can think of?

**Comment by trevor-vaughan** [comment]
@michael-riddle It doesn't have to be changed it just seemed weird that in most of Hiera `--` means "remove this item" and in this case it means "everything besides this item" (I think).

**Comment by michael-riddle** [comment]
> @michael-riddle It doesn't have to be changed it just seemed weird that in most of Hiera `--` means "remove this item" and in this case it means "everything besides this item" (I think).

After some review and discussion, we've decided to go with a '!' over '--' for the negative confinement.

**Review by trevor-vaughan — APPROVED** [review]

**Pull request merged**
