### PR TITLE
(SIMP-8620) Allow confinement to be disabled in compliance mapper

### PR DESCRIPTION
**Pull request by CyrodiilSavior**
[SIMP-8620] #close

[SIMP-8620]: https://simp-project.atlassian.net/browse/SIMP-8620

### CODE REVIEW

**Review by trevor-vaughan — CHANGES_REQUESTED** [review]
Can the documentation be updated to reflect what this is and how to use it please?

**Comment by trevor-vaughan** [comment]
@CyrodiilSavior also, updating the Changelog and version (if applicable) will allow the tests to progress. I can push that as an update for you but not until I know what this change actually does and how to use it.

**Comment by trevor-vaughan** [comment]
@CyrodiilSavior Sorry for the multi-ping but I just realized that we'll need the tests to be updated to test this capability as well.

**Comment by trevor-vaughan** [comment]
Looking at this again, this smells like something in monkey-patching in the library (which is definitely not advised since it's not a guaranteed-stable API).

A better option may be to add an additional option to be passed into the backend configuration via `hiera.yaml` and then propagate the options into the `import` method and toggle confinement at that point.

I'm a little curious about the use case on this since disabling confinement is going to leave you with data in an indeterminate state as multiple OS versions end up overriding options from one another in incompatible ways.

**Comment by trevor-vaughan** [comment]
@CyrodiilSavior  Is this still needed, or can it be closed?

**Comment by silug** [comment]
> @CyrodiilSavior Is this still needed, or can it be closed?

Some variation on this is necessary for reporting purposes.

**Comment by trevor-vaughan** [comment]
@silug It'll need tests to be able to understand how it works and what it's for in the future.

**Pull request closed without merging**
